# Using For Loop extracting R,G,B color values of an image

In [14]:
import cv2
import numpy as np

In [15]:
x=cv2.VideoCapture(0)

In [16]:
ret,image=x.read()

In [17]:
x.release()

In [5]:
image

array([[[22, 19, 15],
        [23, 18, 15],
        [23, 20, 12],
        ...,
        [46, 27, 22],
        [48, 29, 22],
        [48, 29, 22]],

       [[23, 19, 14],
        [23, 19, 14],
        [26, 21, 12],
        ...,
        [44, 28, 22],
        [45, 29, 23],
        [45, 29, 23]],

       [[29, 19, 12],
        [30, 20, 13],
        [30, 21, 12],
        ...,
        [39, 28, 24],
        [41, 29, 25],
        [41, 29, 25]],

       ...,

       [[84, 97, 59],
        [84, 97, 59],
        [83, 95, 59],
        ...,
        [46, 39, 36],
        [46, 39, 36],
        [46, 39, 36]],

       [[84, 94, 64],
        [84, 94, 64],
        [83, 93, 63],
        ...,
        [46, 38, 38],
        [45, 37, 37],
        [45, 37, 37]],

       [[84, 93, 67],
        [84, 93, 67],
        [83, 92, 66],
        ...,
        [45, 37, 37],
        [45, 37, 37],
        [45, 37, 37]]], dtype=uint8)

### Image is a numpy array containing B,G,R values

In [18]:
image1=image

In [19]:
for i in image1:
    for j in i:
        j[0]=0
        j[1]=0    

In [20]:
cv2.imshow('red_image',image1)
cv2.waitKey()
cv2.destroyAllWindows()

In [21]:
image

array([[[ 0,  0, 18],
        [ 0,  0, 18],
        [ 0,  0, 18],
        ...,
        [ 0,  0, 22],
        [ 0,  0, 24],
        [ 0,  0, 24]],

       [[ 0,  0, 18],
        [ 0,  0, 18],
        [ 0,  0, 18],
        ...,
        [ 0,  0, 22],
        [ 0,  0, 24],
        [ 0,  0, 24]],

       [[ 0,  0, 17],
        [ 0,  0, 17],
        [ 0,  0, 17],
        ...,
        [ 0,  0, 22],
        [ 0,  0, 24],
        [ 0,  0, 24]],

       ...,

       [[ 0,  0, 87],
        [ 0,  0, 90],
        [ 0,  0, 95],
        ...,
        [ 0,  0, 37],
        [ 0,  0, 37],
        [ 0,  0, 36]],

       [[ 0,  0, 90],
        [ 0,  0, 92],
        [ 0,  0, 98],
        ...,
        [ 0,  0, 38],
        [ 0,  0, 38],
        [ 0,  0, 37]],

       [[ 0,  0, 92],
        [ 0,  0, 94],
        [ 0,  0, 99],
        ...,
        [ 0,  0, 38],
        [ 0,  0, 38],
        [ 0,  0, 37]]], dtype=uint8)

### Extracting blue colour similarly

In [10]:
image2=image

In [11]:
for i in image2:
    for j in i:
        j[1]=0
        j[2]=0    

In [12]:
cv2.imshow('blue_image',image2)
cv2.waitKey()
cv2.destroyAllWindows()

In [13]:
image2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

### Extracting green colour similarly

In [ ]:
image3=np.array(image)

In [ ]:
for i in image3:
    for j in i:
        j[0]=0
        j[2]=0    

In [ ]:
cv2.imshow('green_image',image3)
cv2.waitKey()
cv2.destroyAllWindows()

# Using Split function and zeros to extract R,G,B color values of an image

In [ ]:
import cv2
import numpy as np

In [ ]:
a1=np.zeros([480,640],dtype="uint8")

In [ ]:
x=cv2.VideoCapture(0)

In [ ]:
ret,image=x.read()

In [ ]:
x.release()

### Getting Blue Color Values

In [ ]:
B,G,R=cv2.split(image)
B_image=cv2.merge([B,a1,a1])

In [ ]:
cv2.imshow('image',B_image)
cv2.waitKey()
cv2.destroyAllWindows()

### Getting Green Color Values

In [ ]:
B,G,R=cv2.split(image)
G_image=cv2.merge([a1,G,a1])

In [ ]:
cv2.imshow('image',G_image)
cv2.waitKey()
cv2.destroyAllWindows()

### Getting Red Color Values

In [ ]:
B,G,R=cv2.split(image)
R_image=cv2.merge([a1,a1,R])

In [ ]:
cv2.imshow('image',R_image)
cv2.waitKey()
cv2.destroyAllWindows()

# Converting Color Image to greyscale

In [ ]:
BW_image=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

In [ ]:
cv2.imshow('image',BW_image)
cv2.waitKey()
cv2.destroyAllWindows()