###### Download IP Webcam app in the phone and start server on the app. Connect the system to the hotspot of mobile and get the IP displayed on the IP Webcam app.

## First we try to capture an image from our mobile camera

In [1]:
import requests

In [31]:
url="http://10.60.133.134:8080/shot.jpg"  #https://"url_on_app"/shot.jpg

In [3]:
data=requests.get(url)

In [4]:
data

<Response [200]>

In [5]:
myphoto=data.content

In [7]:
type(myphoto)

bytes

In [9]:
myphoto_a=bytearray(myphoto)

In [29]:
print(myphoto_a)

bytearray(b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x10\x0b\x0c\x0e\x0c\n\x10\x0e\r\x0e\x12\x11\x10\x13\x18)\x1b\x18\x16\x16\x182$&\x1e);4>=:498AI^PAEYF89RoSYadiji?Os{rfz^gie\xff\xdb\x00C\x01\x11\x12\x12\x18\x15\x180\x1b\x1b0eC9Ceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee\xff\xc0\x00\x11\x08\x06\x00\x08\x00\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04\x04\x00\x00\x01}\x01\x02\x03\x00\x04\x11\x05\x12!1A\x06\x13Qa\x07"q\x142\x81\x91\xa1\x08#B\xb1\xc1\x15R\xd1\xf0$3br\x82\t\n\x16\x17\x18\x19\x1a%&\'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz\x83\x84\x85\x86\x87\x88\x89\x8a\x92\x93\x94\x95\x96\x97\x98\x99\x9a\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xe1\xe2

In [12]:
import numpy as np

In [13]:
photo_1d=np.array(myphoto_a)

In [15]:
photo_1d.shape

(39929,)

In [21]:
import cv2

In [22]:
photo_3d=cv2.imdecode(photo_1d,-1)

In [30]:
print(photo_3d)

[[[63 61 53]
  [64 62 54]
  [65 63 55]
  ...
  [31 39 29]
  [29 37 27]
  [27 35 25]]

 [[64 62 54]
  [65 63 55]
  [66 64 56]
  ...
  [31 39 29]
  [29 37 27]
  [28 36 26]]

 [[65 63 55]
  [66 64 56]
  [67 65 57]
  ...
  [32 40 30]
  [30 38 28]
  [29 37 27]]

 ...

 [[39 46 49]
  [42 49 52]
  [43 50 53]
  ...
  [25 37  0]
  [28 43  0]
  [30 47  0]]

 [[33 40 43]
  [37 44 47]
  [39 46 49]
  ...
  [28 43  0]
  [29 47  0]
  [32 52  0]]

 [[27 34 37]
  [32 39 42]
  [35 42 45]
  ...
  [31 48  0]
  [32 52  0]
  [34 55  0]]]


In [28]:
cv2.imshow("hi",photo_3d)
cv2.waitKey()
cv2.destroyAllWindows()

### Running The previous code on loop to get a live video stream

In [24]:
import requests
import cv2
import numpy

In [26]:
url="http://10.60.133.134:8080/shot.jpg"

In [27]:
while True:
    data=requests.get(url)
    myphoto=data.content
    myphoto_a=bytearray(myphoto)
    photo_1d=numpy.array(myphoto_a)
    photo_3d=cv2.imdecode(photo_1d, -1)
    cv2.imshow('stream',photo_3d)
    if cv2.waitKey(1)==13:
        break
cv2.destroyAllWindows()